CREATE USER gitpod WITH SUPERUSER PASSWORD 'gitpod';

CREATE DATABASE dbt;
GRANT ALL PRIVILEGES ON DATABASE dbt TO gitpod;

CREATE SCHEMA dbt_matt_w;
GRANT ALL PRIVILEGES ON SCHEMA dbt_matt_w TO gitpod;
