version: 2

models:
  - name: fact_order_promos
    description: Orders combined with any used promotion information
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

  - name: fact_page_views
    description: Events combined with user, order and product information
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
